INTERNAL_SERVER_ERROR:
  message: "We have encountered an internal server error."

NOT_FOUND:
  message: "Resource was not found."

UNAUTHORIZED:
  message: "Authentication failed."

INVALID_DATA:
  message: "There is some problem with the data you submitted."